### ISSUE TITLE
TypeError: render_template() missing 1 required positional argument: 'context'

### ISSUE THREAD

**Issue by nihlaeth** [imbolc/aiohttp-login#5]
I ran into the following error using `aiohttp-login`:
```
Error handling request
Traceback (most recent call last):
  File "/var/www/dnd/lib64/python3.6/site-packages/aiohttp/web_server.py", line 62, in handle_request
    resp = yield from self._handler(request)
  File "/var/www/dnd/lib64/python3.6/site-packages/aiohttp/web.py", line 270, in _handle
    resp = yield from handler(request)
  File "/var/www/dnd/lib64/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 115, in middleware
    return (yield from handler(request))
  File "/var/www/dnd/lib64/python3.6/site-packages/aiohttp_session/__init__.py", line 129, in middleware
    response = yield from handler(request)
  File "/var/www/dnd/aiohttp-login/aiohttp_login/flash.py", line 31, in process
    response = await handler(request)
  File "/var/www/dnd/aiohttp-login/aiohttp_login/handlers.py", line 328, in confirmation
    return render_template(themed('confirmation_error.html'), request)
TypeError: render_template() missing 1 required positional argument: 'context'
```

**Comment by imbolc** [comment]
Hey :) Have you tried to update version of `aiohttp_jinja2`?

**Comment by nihlaeth** [comment]
Hello again :)

Unfortunately that won't solve the problem because, as you can see [here in the master branch of `aiohttp_jinja2`](https://github.com/aio-libs/aiohttp-jinja2/blob/master/aiohttp_jinja2/__init__.py#L67), context is a required argument.

**Comment by imbolc** [comment]
Yes, you're right, I was sure they made context optional from some version, now I see they just allow it be None. Would you provide PR?

**Comment by nihlaeth** [comment]
Sure! Could you make a new release with this fix then?

**Comment by imbolc** [comment]
Merged, thanks :)
